name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
      - main
      - development
  pull_request: true

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build and test site
        run: |
          gem install jekyll bundler
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
