safe: false

url: "https://gedichtenkoffer.nl"

author: Sonja Zuijdervelt

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll_picture_tag
  - kramdown-parser-gfm

picture:
  ignore_missing_images: true

last-modified-at:
  date-format: '%d-%b-%y'
