safe: false

plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - kramdown-parser-gfm
