source "https://rubygems.org"

gem "cssminify2", "~> 2.0"
gem "htmlcompressor", "~> 0.2.0"
gem "jekyll", "~> 4.2.0"
gem "jekyll-default-layout", "~> 0.1.4"
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-include-cache", "~> 0.2.0"
gem "jekyll-last-modified-at", "~> 1.3"
gem "jekyll-optional-front-matter", "~> 0.3.2"
gem "jekyll-readme-index", "~> 0.3.0"
gem "jekyll-relative-links", "~> 0.6.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-titles-from-headings", "~> 0.5.3"
gem "jekyll_picture_tag", "~> 2.0.0"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "nokogiri", "~> 1.12.3"
gem "rufo", "~> 0.12.0"
gem "uglifier", "~> 4.2.0"
gem "webrick", "~> 1.7"
